[project]
name = "tutorials-clean"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "isofit>=3.7",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "mkdocs>=1.6.1",
    "mkdocs-nbconvert>=0.5",
]
